"""add_chat_sessions

Revision ID: 695aef4d438c
Revises: 1b2c3d4e5f60
Create Date: 2026-06-14 16:45:22.230935
"""
from alembic import op
import sqlalchemy as sa


revision = '695aef4d438c'
down_revision = '1b2c3d4e5f60'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

